config/routes.rb
Rails.application.routes.draw do

  get 'tags/:tag', to: 'home#index', as: :tag

  root 'home#index'

  get 'home/index'

  get 'home/about'

  get 'home/contact'

  devise_for :users
  devise_for :viewers, :controllers => { :omniauth_callbacks => "viewers/omniauth_callbacks" }

  devise_scope :viewer do
    get 'sign_out', :to => 'viewers/sessions#destroy' #, :as => :destroy_viewer_session
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'sample/index'

  concern :commentable do

    resources :comments

  end

  resources :sections, only: [:show] do
      resources :articles, :serials, only: [:index, :show] do
     concerns :commentable
   end
  end

  resources :articles, :serials, only: [:index, :show] do
     concerns :commentable
   end

  match ':controller(/:action(/:id(.:format)))', :via => :get
end

app/models/serial.rb
class Serial < ActiveRecord::Base
  include Commentable


  belongs_to :section, polymorphic: true
  has_many :articles

  mount_uploader :header, HeaderUploader
  acts_as_taggable




  scope :published, -> {where(published: true)}
  scope :featured, -> {where(featured: true)}

 def related_tags
    @serial.find_related_tags
  end

  
 rails_admin do
  configure :tag_list
end


end

app/controllers/serials_controller.rb
class SerialsController < ApplicationController
#  before_action :set_serial, only: [:show, :edit, :update, :destroy]
  before_action :set_serial, :set_section,only: [:show]

  # GET /serials
  # GET /serials.json
  def index
    @serials = Serial.all
  end

  # GET /serials/1
  # GET /serials/1.json
  def show
    @commentable = @serial
    @comments= @commentable.comments
    @comment = Comment.new
  end

=begin
  # GET /serials/new
  def new
    @serial = Serial.new
  end

  # GET /serials/1/edit
  def edit
  end

  # POST /serials
  # POST /serials.json
  def create
    @serial = Serial.new(serial_params)

    respond_to do |format|
      if @serial.save
        format.html { redirect_to @serial, notice: 'Serial was successfully created.' }
        format.json { render :show, status: :created, location: @serial }
      else
        format.html { render :new }
        format.json { render json: @serial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /serials/1
  # PATCH/PUT /serials/1.json
  def update
    respond_to do |format|
      if @serial.update(serial_params)
        format.html { redirect_to @serial, notice: 'Serial was successfully updated.' }
        format.json { render :show, status: :ok, location: @serial }
      else
        format.html { render :edit }
        format.json { render json: @serial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /serials/1
  # DELETE /serials/1.json
  def destroy
    @serial.destroy
    respond_to do |format|
      format.html { redirect_to serials_url, notice: 'Serial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
=end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_serial
      @serial = Serial.find(params[:id])

    end
    def set_section
      @section = Section.find(params[:section_id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def serial_params
      params.require(:serial).permit(:name, :description, :section_id, :section_type, :tag_list => [])
    end
end

app/helpers/serials_helper.rb
module SerialsHelper
end

app/views/serials/_form.html.erb
<%= form_for(@serial) do |f| %>
  <% if @serial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@serial.errors.count, "error") %> prohibited this serial from being saved:</h2>

      <ul>
      <% @serial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :section_id %><br>
    <%= f.text_field :section_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/serials/_header.html.erb
<% postPrefix = @section.name.parameterize.underscore.camelize(:lower) %>
<%= content_tag(:div, class: "headerContainer #{postPrefix}HeaderContainer") do %>
	<style>
	.serialHeader{ background-image: url(<%= @serial.header.url %>); background-size: cover;background-position: center;  background-repeat: no-repeat; }
		</style>
		<%= content_tag(:div, class: "header serialHeader #{@section.name.parameterize.underscore.camelize(:lower)}Header") do %>
		<%= content_tag(:div, content_tag(:h1, @serial.name), class: "headerTitle #{postPrefix}HeaderTitle")%>
		
		<% end %>
	<%= content_tag(:div, class: "headerDetails #{postPrefix}HeaderDetails" ) do %>
			<%= content_tag(:h1, @serial.description, class: "headerDetailsText") %>
			<% end %>
<% end %>

app/views/serials/_infoBox.html.erb
<div class = "infoBox">
	<style>
	.infoImageContainer, .imageLink  { background-image: url(<%= serial.header.url(:thumb) %>); background-size: cover;background-position: center;  background-repeat: no-repeat; }
	</style>
	<%= link_to section_serial_url(serial.section_id, :id => serial.id), class: "imageLink" do  %>
	<div class = "infoImageContainer" >
	</div>
	<% end %>
	
	
	<div class = "info SerialInfo">
		<h1 class = "serialName"> <%= link_to "#{serial.name}", section_serial_url(serial.section_id, :id => serial.id)  %> <%= "#{serial.articles.length }"%></h1>
		<h2 class = "iBoxDescription serialDescription"> <%= truncate(serial.description, length: 50) %> </h2>
		<h3 class = "serialDate"> <%= serial.created_at.to_formatted_s(:long_ordinal) %> </h3>
	</div>
</div>

app/views/serials/edit.html.erb
<h1>Editing Serial</h1>

<%= render 'form' %>

<%= link_to 'Show', @serial %> |
<%= link_to 'Back', serials_path %>

app/views/serials/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Serials</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Section</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @serials.each do |serial| %>
    <tr>
      <td><%= serial.name %></td>
      <td><%= serial.description %></td>
      <td><%= serial.section %></td>
      <td><%= link_to 'Show', serial %></td>
      <td><%= link_to 'Edit', edit_serial_path(serial) %></td>
      <td><%= link_to 'Destroy', serial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Serial', new_serial_path %>

app/views/serials/new.html.erb
<h1>New Serial</h1>

<%= render 'form' %>

<%= link_to 'Back', serials_path %>

app/views/serials/show.html.erb
<%= render "header" %>


<% postPrefix = @section.name.parameterize.underscore.camelize(:lower) %>
<%= content_tag :div, class: "recentDiv recentPostsDiv recentArticlesDiv #{postPrefix}Recents " do %>
	
	<div class = "infoBoxGallery">

	<% if @serial.articles.published.length >0  %>

	<%= render partial: "articles/infoBox", collection: @serial.articles.published, as: :article %>

	<% else %>
	<p> No Published Content Yet </p>

	<% end %>
		
	</div>
	

<% end %>