config/routes.rb
Rails.application.routes.draw do

  get 'tags/:tag', to: 'home#index', as: :tag

  root 'home#index'

  get 'home/index'

  get 'home/about'

  get 'home/contact'

  devise_for :users
  devise_for :viewers, :controllers => { :omniauth_callbacks => "viewers/omniauth_callbacks" }

  devise_scope :viewer do
    get 'sign_out', :to => 'viewers/sessions#destroy' #, :as => :destroy_viewer_session
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'sample/index'

  concern :commentable do

    resources :comments

  end

  resources :sections, only: [:show] do
      resources :articles, :serials, only: [:index, :show] do
     concerns :commentable
   end
  end

  resources :articles, :serials, only: [:index, :show] do
     concerns :commentable
   end

  match ':controller(/:action(/:id(.:format)))', :via => :get
end

app/models/article.rb
class Article < ActiveRecord::Base

  include Commentable

  belongs_to :section, polymorphic: true
  belongs_to :serial, polymorphic: true
  mount_uploader :header, HeaderUploader


  has_many :images
  has_many :scripts
  has_many :datasets
  acts_as_taggable


  scope :standalone, -> {where(serial_id: nil)}
  # scope :firstFeature, -> {where(featur: nil)}


  scope :published, -> {where(published: true)}
  scope :featured, -> {where(featured: true)}


  # searchable do
  #   text :name, boost: 5
  #   text :content
  #   text :comments do
  #     comments.map(&:content)
  #   end

  # end



  # def showData(dPath)
  #   File.read(dPath)

  # end


  def related_tags
    @article.find_related_tags
  end

  def imageArray

    images.to_a


  end

  def dataURLs
    datasets.map do |dSet|
      dSet.data_url

    end

  end

  def getURL(index)
    gon.gotURL = self.dataURLs[index]

  end


  def getFile(index)
    self.dataFiles(index)
    # return allFiles(index)
    gon.data_url


  end


  def dataFiles
    datasets.map do |dSet|
      dSet.data.file

    end

  end

  def dataContents
    datasets.map do |dSet|
      dSet.data.read

    end

  end

  rails_admin do
    configure :tag_list
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :authorable, polymorphic: true
  belongs_to :commentable, polymorphic: true
end

app/models/dataset.rb
class Dataset < ActiveRecord::Base
  belongs_to :article, polymorphic: true
  mount_uploader :data, DataUploader

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :article, polymorphic: true
  mount_uploader :img, ImgUploader
end

app/models/script.rb
class Script < ActiveRecord::Base
  belongs_to :article, polymorphic: true
  mount_uploader :jscript, JscriptUploader

end

app/models/section.rb
class Section < ActiveRecord::Base
	has_many :articles
	has_many :serials
	# has_many :comments, as: :commentable

	mount_uploader :header, HeaderUploader

	acts_as_tagger

	def set_writable_tags
		self.articles.each do |article|
			if article.tags.length >0 
				subTagList = article.tags 
			self.tag(article, :with => subTagList, on: :tags)
				
			end
			
		end

	end


end

app/models/serial.rb
class Serial < ActiveRecord::Base
  include Commentable


  belongs_to :section, polymorphic: true
  has_many :articles

  mount_uploader :header, HeaderUploader
  acts_as_taggable




  scope :published, -> {where(published: true)}
  scope :featured, -> {where(featured: true)}

 def related_tags
    @serial.find_related_tags
  end

  
 rails_admin do
  configure :tag_list
end


end

app/models/tag.rb
class Tag < ActiveRecord::Base
  #belongs_to :article, polymorphic: true
  #belongs_to :section, polymorphic: true

  #has_many :articles
  #mount_uploader :header, HeaderUploader
  #acts_as_taggable

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :comments, as: :authorable, class_name: "User"

  def screenname
    self.email
  end

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
end

app/models/viewer.rb
class Viewer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  has_many :comments, as: :authorable, class_name: "Viewer"


  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |viewer|
      viewer.email = auth.info.email
      viewer.password = Devise.friendly_token[0,20]
      viewer.screenname = auth.info.name   # assuming the viewer model has a name
      # viewer.image = auth.info.image # assuming the viewer model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |viewer|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        viewer.email = data["email"] if viewer.email.blank?
      end
    end
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@sections = Section.includes(:serials, :articles).all


  	if params[:tag]
  		# @tag = Tag.find(params[:tag])
  		# @tagName = @tag.name
  		# @articles = Article.tagged_with(@tagName)
  		# @serials = Serial.tagged_with(@tagName)
      @tag = params[:tag]

      @articles = Article.tagged_with(@tag)
      @serials = Serial.tagged_with(@tag)
  	else
  	@articles = Article.all
    # @featuredPosts = Article.feat
#  	@articles = Article.all.paginate(:page => params[:page], :per_page => 1)
    @serials = Serial.all
	end


  end

  def about
      @sections = Section.includes(:serials, :articles).all

  end

  def contact
  end
end

app/controllers/sample_controller.rb
class SampleController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
def article_path(article)
  # every article record should have a reference to its parent project
  section_article_path(article.section_id, article)
end

def article_comment_path(article, comment)
  # every article record should have a reference to its parent project
  section_article_comment_path(article.section_id, article, comment)
end

def edit_article_comment_path(article, comment)
  # every article record should have a reference to its parent project
  edit_section_article_comment_path(article.section_id, article, comment)
end
  def markdown(source)
    Kramdown::Document.new(source).to_html.html_safe
  end


def kramdown(text)
  return sanitize Kramdown::Document.new(text, {enable_coderay: true, coderay_css: :class}).to_html
end

def preprocess(content)
	result = ERB.new(content).result
	
end

end

app/helpers/articles_helper.rb
module ArticlesHelper


def article_path(article)
  # every article record should have a reference to its parent project
  section_article_path(article.section_id, article)
end

 def showData(dPath)
    File.read("#{Rails.root}#{dPath}")
    
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sample_helper.rb
module SampleHelper
end

app/helpers/sections_helper.rb
module SectionsHelper

  def show_owned_tags(section)
    section.owned_tags.each do |tag|
      content_tag(:h1, tag.name, class: "ownedTag")


    end
  end

end

app/helpers/serials_helper.rb
module SerialsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>YungMorpheus | Autodidact Diaries </title>
        <%= Gon::Base.render_data({}) %>
        
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= stylesheet_link_tag 'main', media: 'all', 'data-turbolinks-track' => true %>
        
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        
        
        <%= csrf_meta_tags %>
    </head>
    <body>
        <%= include_gon(:init => true) %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <div id="fb-root"></div>
        <%= javascript_include_tag "fbAuth" %>
        <div class = "main">
            
            <div class = "mainContent">
                <%= render "shared/siteHeader", locals: { sections: @sections} %>
                <%= yield %>
            </div>
        </div>
        <div class="scriptDiv" data-turbolinks-track = "true">
            <script type="text/javascript">   Turbolinks.allowLinkExtensions('js');</script>
        </div>
    </body>
</html>

app/views/shared/_sectionTags.html.erb
<div class = "sectionClouds">
<div class="tagCloud">
	<% @sharedSections.each do |section| %>
	<% postPrefix = section.name.parameterize.underscore.camelize(:lower) %>

		<% tag_cloud section.owned_tags, %w[s m l] do |tag, css_class| %>
		<%= link_to "#{tag.name}", tag_path(tag.name), class: "#{ css_class } #{postPrefix}TagLink"%>
		<% end %>
	
	<% end %>
	</div>
</div>

app/views/shared/_siteHeader.html.erb
<div class = "siteHeader">
	<div class="siteHeaderFlex">
		<div class = "headerInterior">
			<div id = "siteImageContainer"> <%=  link_to (image_tag "catPic.png", class: "siteHeaderImage" ), root_path %> </div>
			<div id = "siteHeaderText">
				<span><h1 id = "siteName"> <%= link_to "yungMorpheus", root_path, class: "topLink" %> </h1>
				<h2 id = "siteSubtitle"> Autodidact Diaries </h2></span>
			</div>
		</div>
		<div class = "navBlock"><%= render "shared/topNav" %></div>
	</div>
	<div class=" siteHeaderInline ">
		<div class = "viewerDetails">
			<% if viewer_signed_in?  %>
			<p> <%= "Welcome, #{current_viewer.screenname}" %> </p>
			<% else %>
			<%= link_to "Sign in with Facebook", viewer_omniauth_authorize_path(:facebook) %>
			
			<%end%>
			<%= link_to "Sign Out", :destroy_viewer_session, method: :delete %>
		</div>
		<%= render "shared/sectionTags" %>
		<%#= form_tag articles_path, class: "siteSearch", :method => :get do %>
		<!-- <p> -->
			<%#= text_field_tag :search, params[:search] %>
			<%#= submit_tag "Search", :name => nil %>
		<!-- </p> -->
		<%# end %>
	</div>
	
</div>

app/views/shared/_topNav.html.erb
<ul class = "navList">
	
	<li class = "navListItem "><%= link_to "ABOUT", home_about_path, class: "navLink" %></li>
	<% @sharedSections.each do |section| %>
	<li class = "navListItem "><%= link_to "#{section.name.upcase}", section_path(section), class: "navLink", id: "#{section.name}"+"NavLink" %></li>

	
	<%end%>
	<li class = "navListItem "><%= link_to "CONTACT", home_contact_path, class: "navLink" %></li>
</ul>