config/routes.rb
Rails.application.routes.draw do

  get 'tags/:tag', to: 'home#index', as: :tag

  root 'home#index'

  get 'home/index'

  get 'home/about'

  get 'home/contact'

  devise_for :users
  devise_for :viewers, :controllers => { :omniauth_callbacks => "viewers/omniauth_callbacks" }

  devise_scope :viewer do
    get 'sign_out', :to => 'viewers/sessions#destroy' #, :as => :destroy_viewer_session
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'sample/index'

  concern :commentable do

    resources :comments

  end

  resources :sections, only: [:show] do
      resources :articles, :serials, only: [:index, :show] do
     concerns :commentable
   end
  end

  resources :articles, :serials, only: [:index, :show] do
     concerns :commentable
   end

  match ':controller(/:action(/:id(.:format)))', :via => :get
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@sections = Section.includes(:serials, :articles).all


  	if params[:tag]
  		# @tag = Tag.find(params[:tag])
  		# @tagName = @tag.name
  		# @articles = Article.tagged_with(@tagName)
  		# @serials = Serial.tagged_with(@tagName)
      @tag = params[:tag]

      @articles = Article.tagged_with(@tag)
      @serials = Serial.tagged_with(@tag)
  	else
  	@articles = Article.all
    # @featuredPosts = Article.feat
#  	@articles = Article.all.paginate(:page => params[:page], :per_page => 1)
    @serials = Serial.all
	end


  end

  def about
      @sections = Section.includes(:serials, :articles).all

  end

  def contact
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<div class = "headerContainer">
	<div class = "header homeHeader">
	<div id="homeSlider"><% @sections.each do |sect|%>
	<% firstFeature = sect.articles.featured.first || sect.articles.first %>
	<%= link_to(section_article_path(firstFeature.section_id, :id => firstFeature.id)) do  %>
	<%=image_tag(sect.header.url, alt: "#{firstFeature.name}", "data-src": sect.header.url) %>
		<%#= %>
			
	
			<% end  %>
			<% end  %>
	</div>


	</div>
</div>

app/views/home/_recentArticles.html.erb
<div class = "recentDiv recentArticlesDiv" ><div class = "sectionLabel">
	<span><div class = "recentLabel recentArticleLabel" ><h1 class="labelText"> <%= link_to "#{section.name}", section_path(section) %></h1></div></span>
	<p> this will render the infoboxes</p></div>
	<div class = "infoBoxGallery">
		<%= render partial: "articles/infoBox", collection: section.articles, as: :article %>
	</div>
</div>

app/views/home/_recentPosts.html.erb
<%= content_tag :div, class: "recentDiv recentPostsDiv #{section.name.parameterize.underscore.camelize(:lower)}Recents " do %>
<div class = "sectionLabel">
	<span><div class = "recentLabel recentPostsLabel" ><h1 class="labelText"> <%= link_to "#{section.name}", section_path(section) %></h1></div></span>
	</div>

	
	<div class = "infoBoxGallery">

	<% if section.articles.published.standalone.length >0  %>

	<%= render partial: "articles/infoBox", collection: section.articles.published.standalone, as: :article %>

	<% else %>
	<p> No Published Articles Yet </p>

	<% end %>
		
</div>
		
	<div class = "infoBoxGallery">
		
<% if section.serials.published.length >0  %>

	<%= render partial: "serials/infoBox", collection: section.serials.published, as: :serial %>

	<% else %>
	<p> No Published Serials Yet </p>

	<% end %>
		
	</div>

<%  end %>

app/views/home/_recentSerials.html.erb
<div class = "recentDiv recentSerialsDiv" >
	<div class = "sectionLabel">
		<h1 class = "recentLabel recentSerialLabel" > <%=section.name%> </h1>
		<p> this will render the infoboxes</p>
	</div>
	
	<div class = "infoBoxGallery">
		<%= render partial: "serials/infoBox", collection: section.serials, as: :serial %>
	</div>
</div>
<!--
<div class = "recentDiv" id = "recentSerialsDiv">
	<h1 class = "recentLabel" id = "recentSerialLabel"> <%= section.name%> </h1>
	<p> this will render the infoboxes</p>
</div> -->

app/views/home/_taggedPosts.html.erb
<%= content_tag :div, class: "recentDiv recentPostsDiv taggedDiv" do %>
	<div class = "infoBoxGallery">
		<%= render partial: "articles/infoBox", collection: @articles.uniq, as: :article %>
	</div>
	<div class = "infoBoxGallery">
		<%= render partial: "serials/infoBox", collection: @serials.uniq, as: :serial %>
	</div>
<% end %>

app/views/home/about.html.erb
<div class = "content aboutContent">
	<h1> I am an artist, graphic designer, and visual history nerd in love with the internet.</h1>
	<p>After a long period of underemployment, and seeing a lot of my friends go through coding bootcamps, I decided to abandon my (albeit fledgling) art practice and become a web developer. How hard could it be? </p>
	<div class="imageContainer">	<%= image_tag "yungMorpheusAbout.png", class: "aboutPortrait postImageSingle" %>
	</div>	<h1><strong>Harder than I thought, turns out.</strong></h1>
	<p>  With no formal CS education, and the internet as my teacher, I've spent over two years studying all manner of mathematics, computer science, physics, chemistry, and even a brief stint with electrical engineering (thanks Arduino!). And this hands-on multi-modal instruction hasgiven me a depth and breadth of experience that I would unlikely be exposed to in a three-month bootcamp. Here is a selection of books I've read more-or-less cover-to-cover.</p>
	<ul class="resources">
	</ul>
	<p> Though this unrefined, shotgun-ethos  has yet to put me in any place to "snatch those coins," I have become <strong>intensely</strong> interested in the cultural implications of all I've been exposed to. It's particularly difficult to explain, my excitement, but there are moments when I get to barely brush against something powerful. Now, things like "systems of oppression" and "sentence structure" begin to take on explicit geometrical forms. Strangely enough, having dropped being an "artist" I havent felt more inspired than I do now. But these ideas have been sitting in the back of my mind as I spend time trying to find employment. During that process, I've been told that I lack experience from numerous companies, and so this blog has at least three purposes: </p>
	<ol class="blogUses">
		
		<li >to establish a few scripts and applications that I can show to employers</li>
		<li >to demonstrate the range of knowledge</li>
		<li> to document my process of digital discovery</li>
	</ol>
	
	<h1>The Blog is broken into a few sections:</h1>
	<ul>
		<li class = "everydayAlgorithmsAbout">
			<strong > 	<%= link_to section_path(2), class: "imageContainer"  do  %>
			<% section = @sections[0] %>
			<p class="aboutHeader">"Everyday Algorithms"</p>
			<%= image_tag section.header.url, alt: "#{section.name}", class: "aboutImage postImageSingle" %>
			<% end %>
			</strong>
			<p> In this section, I will look at small instances of my daily life that I see can be helped along by some computer science. Things such as getting dressed in hte morning, managing household chores, and responding to facebook messages. Much of this section will be a consciously overwrought application of computation to my daily life, but will likely demonstrate the ways in which we all make use of certain algorithmic thinking without even noticing it. It will also exercise my coding skills. </p></li>
			<li class = "visualizationsAbout"> <strong > <%= link_to section_path(3), class: "imageContainer" do  %>
				<% section = @sections[1] %>
				<p class="aboutHeader"><%= "#{section.name}"%></p>
				<%= image_tag section.header.url, alt: "#{section.name}", class: "aboutImage postImageSingle" %>
				<% end %> </strong>
				<p> In this section, I will produce data visualizations from information I findon the web, and dive more deeply into my practice of making visual art in a digital environment. I will make use mostly of d3.js and the R programming language for statistics. There are many formsof data visualization beyond standard bar/line charts and I am interested in giving myself the challenge of making sense of them on my own.</p>
			</li>
			<li class = "cultureAbout"> <strong ><%= link_to section_path(7), class: "imageContainer"  do  %>
				<% section = @sections[2] %>
				<p class="aboutHeader"><%= "#{section.name}"%></p>
				<%= image_tag section.header.url, alt: "#{section.name}", class: "aboutImage postImageSingle" %>
				<% end %> </strong>
				<p> This section of the site explores the many subtle connections I feel that the advent of digital technolodies have had on our lives. I am particularly interested in how the experiences of excess and irreverence so popular online (e.g. buzzfeed and reddit) connect with a culture that atleast on its face, promotes prudence and professionalism. I also think pornography is a very fertileplace to discuss how art and culture collide (rememeber the interenet's rule 34?). I'm also a bit of an academic, so there'll likely be some intellectual rambling here. </p>
			</li>
			<li class = "projectsAbout"> <strong ><%= link_to section_path(6), class: "imageContainer"  do  %>
				<% section = @sections[3] %>
				<p class="aboutHeader"><%= "#{section.name}"%></p>
				<%= image_tag section.header.url, alt: "#{section.name}", class: "aboutImage postImageSingle " %>
				<% end %> </strong>
				<p> Here I will document soem examples of my previous work and some projects that I am working on. I do imagine a lot of the things in this section will be solidified versions of things I discuss in other sections. </p></li>
				<li class = "programmingAbout"> <strong > <%= link_to section_path(4), class: "imageContainer"  do  %>
					<% section = @sections[4] %>
					<p class="aboutHeader"><%= "#{section.name}"%></p>
					<%= image_tag section.header.url, alt: "#{section.name}", class: "aboutImage postImageSingle" %>
					<% end %>  </strong>
					<p>This section will be the basis for many of the posts in the above sections. Here I will establish the basics of my application development experience. Because of my unorthodox training, I've been exposed to a number of programming languages and theories and, if only for the sake of clairifying my heterogenous understanding, I will put down in my own language things like data strucutures and design patterns. If I do a good enough job with the Search Engine Optimization, maybe this info can help someone else out there</p></li>
				</ul>
			
			</div>

app/views/home/contact.html.erb
<div class="content contactContent"> 
	<div class="contactSection imageContainer">
		<%= link_to "https://www.linkedin.com/in/tfpractice" do %>
		
		<%= image_tag "linkedInLogo.png", class: "contactImage postImageSingle"%>
		<% end %>
	</div>



	<div class="contactSection imageContainer">
		<%= link_to "http://codepen.io/tfpractice/" do %>
		
		<%= image_tag "codePen.png", class: "contactImage postImageSingle"%>
		<% end %>
	</div>
<div class="contactSection imageContainer">
		<%= link_to "https://github.com/tfpractice" do %>
		
		<%= image_tag "gitHub.png", class: "contactImage postImageSingle"%>
		<% end %>
	</div>

	<div class="contactSection imageContainer">
		<%= link_to "http://tfpsite4.herokuapp.com/" do %>
		
		<%= image_tag "tfpPortfolio.png", class: "contactImage postImageSingle"%>
		<% end %>
	</div>
</div>

app/views/home/index.html.erb
<div class = "homeContent">
	
	<%#= link_to "sing in", "auth/facebook" %> 
	<%= render 'header' %>
<% if params[:tag] %>


	<%= render partial: "taggedPosts" %>
<%#= @articles.tagged_with(:tag).each do |article| %>
	<%# render partial: "articles/infoBox", object: article %>
	<%# end %>
<% else %>
		<%= render partial: 'recentPosts', collection: @sections, as: :section %>

<% end %>
	<%# render partial: 'recentPosts', collection: @sections, as: :section %>
</div>

app/views/home/showSection.html.erb
<p> THIS IS THE EXAMPLE</p>
<%= @section.name %>