config/routes.rb
Rails.application.routes.draw do

  get 'tags/:tag', to: 'home#index', as: :tag

  root 'home#index'

  get 'home/index'

  get 'home/about'

  get 'home/contact'

  devise_for :users
  devise_for :viewers, :controllers => { :omniauth_callbacks => "viewers/omniauth_callbacks" }

  devise_scope :viewer do
    get 'sign_out', :to => 'viewers/sessions#destroy' #, :as => :destroy_viewer_session
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'sample/index'

  concern :commentable do

    resources :comments

  end

  resources :sections, only: [:show] do
      resources :articles, :serials, only: [:index, :show] do
     concerns :commentable
   end
  end

  resources :articles, :serials, only: [:index, :show] do
     concerns :commentable
   end

  match ':controller(/:action(/:id(.:format)))', :via => :get
end

app/models/section.rb
class Section < ActiveRecord::Base
	has_many :articles
	has_many :serials
	# has_many :comments, as: :commentable

	mount_uploader :header, HeaderUploader

	acts_as_tagger

	def set_writable_tags
		self.articles.each do |article|
			if article.tags.length >0 
				subTagList = article.tags 
			self.tag(article, :with => subTagList, on: :tags)
				
			end
			
		end

	end


end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
#  before_action :set_section, only: [:show, :edit, :update, :destroy]
  before_action :set_section, only: [:show]
  before_action :set_writable_tags

  # GET /sections
  # GET /sections.json
  def index
    render 'home/index'
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    # @commentable = @section
    # @comments= @commentable.comments
    # @comment = Comment.new
  end

  # GET /sections/new
=begin  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
=end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_writable_tags
      @section.set_writable_tags
      
    end
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:name, :description, :published)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper

  def show_owned_tags(section)
    section.owned_tags.each do |tag|
      content_tag(:h1, tag.name, class: "ownedTag")


    end
  end

end

app/views/sections/_form.html.erb
<% 
=begin %>
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 =end%> 
 #%>

app/views/sections/_header.html.erb
<% postPrefix = @section.name.parameterize.underscore.camelize(:lower) %>
<%= content_tag(:div, class: "headerContainer #{postPrefix}HeaderContainer") do %>
	<style>
	.sectionHeader{ background-image: url(<%= @section.header.url %>); background-size: cover;background-position: center;  background-repeat: no-repeat; }
	</style>
		<%= content_tag(:div, class: "header sectionHeader #{@section.name.parameterize.underscore.camelize(:lower)}Header") do %>
		<%= content_tag(:div, content_tag(:h1, @section.name), class: "headerTitle #{postPrefix}HeaderTitle")%>
		
		<% end %>
	<%= content_tag(:div, class: "headerDetails #{postPrefix}HeaderDetails" ) do %>
			<%= content_tag(:h1, @section.description, class: "headerDetailsText") %>
			<% end %>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form' %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Sections</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @sections.each do |section| %>
    <tr>
      <td><%= section.name %></td>
      <td><%= section.description %></td>
      <td><%= section.published %></td>
      <td><%= link_to 'Show', section %></td>
      <td><%= link_to 'Edit', edit_section_path(section) %></td>
      <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<%#= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form' %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<% postPrefix = @section.name.parameterize.underscore.camelize(:lower) %>
<%= content_tag(:div, class: "#{postPrefix}MainContent") do %>
<!-- <p id="notice"><%= notice %></p> -->
<%= render 'header'%>

<% if @section.owned_tags.length > 0 %>
<div class="sectionTags content justSecond">
	<h2 class="largeHeaderText"> Tags in this section</h2>
	<% @section.owned_tags.each do |tag| %>
	<%= link_to "#{tag.name}",  tag_path(tag.name) %>
	<% @section.articles.tagged_with(tag.name).uniq do |art| %>
	<%= art.name %>
	<% end %>
	<% end %>
</div>

<% end %>
<%= content_tag :div, class: "recentDiv recentPostsDiv #{@section.name.parameterize.underscore.camelize(:lower)}Recents " do %>
<header class="recentLabel recentArticlesLabel recentPostsLabel">
	<h1 class = "labelText" > Articles </h1>
</header>
<div class = "infoBoxGallery">
<% if @section.articles.published.standalone.length >0  %>

	<%= render partial: "articles/infoBox", collection: @section.articles.published.standalone, as: :article %>

	<% else %>
	<p> No Published Content Yet </p>

	<% end %>
		
</div>
<%  end %>
<%= content_tag :div, class: "recentDiv recentPostsDiv #{@section.name.parameterize.underscore.camelize(:lower)}Recents " do %>
<header class="recentLabel recentSerialsLabel recentPostsLabel">
	<h1 class = "labelText" > Serials </h1>
</header>
<div class = "infoBoxGallery">

<% if @section.serials.published.length >0  %>

	<%= render partial: "serials/infoBox", collection: @section.serials.published, as: :serial %>

	<% else %>
	<p> No Published Content Yet </p>

	<% end %>
		
</div>
<!-- </div> -->
<%  end %>
<% end %>